// front_end-frameworks/vue/src/components/ui/Button.vue
<script setup>
defineProps({
  href: { type: String, required: true },
  variant: { type: String, default: "primary" },
  target: { type: String, default: null },
  rel: { type: String, default: null },
});

const baseClasses = "px-4 py-2 font-semibold rounded-md transition-colors";
</script>

<template>
  <a :href="href" :target="target" :rel="rel" :class="[baseClasses, variant === 'primary' ? 'bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40 text-slate-50' : 'border border-slate-800 bg-slate-950 hover:bg-slate-900 text-slate-50']">
    <slot />
  </a>
</template>

// front_end-frameworks/svelte/src/components/ui/Button.svelte
<script>
  let { href, variant = "primary", target = null, rel = null, children } = $props();

  const baseClasses = "px-4 py-2 font-semibold rounded-md transition-colors";
</script>

<a {href} {target} {rel} class="{baseClasses} {variant === 'primary' ? 'bg-violet-500 hover:bg-violet-600 shadow-lg shadow-violet-500/40 text-slate-50' : 'border border-slate-800 bg-slate-950 hover:bg-slate-900 text-slate-50'}">
  {@render children?.()}
</a>
